name = "cloudflare-telegram-bot-worker-shop"
main = "src/index.ts"
compatibility_date = "2024-01-29"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "prod-d1-tutorial"
database_id = "16622727-7b5a-46e7-906b-5eb2dd2321bb"
